### ISSUE TITLE
购买市场物品界面时 显示当前购买的物品槽位消失了 

### ISSUE THREAD

**Issue by ASLCH** [liaojinmin/GeekMail-Pro#10]
购买市场物品界面时 显示当前购买的物品槽位消失了  点击后会有报错

**Comment by ASLCH** [comment]
[21:49:54 ERROR]: Could not pass event InventoryClickEvent to GeekMail-Pro v3.0
kotlin1720.NotImplementedError: An operation is not implemented.
        at me.geek.mail.common.menu.action.MarketBuyMenu.onClick(MarketBuyMenu.kt:84) ~[?:?]
        at me.geek.mail.common.menu.MenuListener.onClick(MenuListener.kt:48) ~[?:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source) ~[?:1.8.0_171]
        at me.geek.mail.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
        at me.geek.mail.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132) ~[?:?]
        at me.geek.mail.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130) ~[?:?]
        at me.geek.mail.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[?:?]
        at me.geek.mail.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76) ~[?:?]
        at me.geek.mail.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
        at me.geek.mail.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
        at me.geek.mail.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at me.geek.mail.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at me.geek.mail.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1893) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
[
