### ISSUE TITLE
1.19.4 无法发送邮件

### ISSUE THREAD

**Issue by MoeShimaKaze** [liaojinmin/GeekMail-Pro#15]
使用命令/gkm mail 玩家 MAIL_ITEM Test Test，首次执行时能正常打开GUI放置物品，也能正常收到邮件
但是关闭GUI时出现如下报错
`_[13:38:24 ERROR]: Could not pass event InventoryCloseEvent to GeekMail-Pro v3.3.2
java.lang.NoSuchMethodError: 'net.minecraft.server.v1_19_R3.ItemStack org.bukkit.craftbukkit.v1_19_R3.inventory.CraftItemStack.asNMSCopy(org.bukkit.inventory.ItemStack)'
at me.geek.mail.taboolib.module.nms.NMSGenericImpl.getName(NMSGenericImpl.java:119) ~[?:?]
at me.geek.mail.taboolib.module.nms.NMSI18nKt.getInternalName(NMSI18n.kt:28) ~[GeekMail-Pro-3.3.2.jar:?]
at me.geek.mail.taboolib.module.nms.i18n.I18nLegacy.getName(I18nLegacy.java:87) ~[GeekMail-Pro-3.3.2.jar:?]
at me.geek.mail.taboolib.module.nms.NMSI18nKt.getI18nName(NMSI18n.kt:32) ~[GeekMail-Pro-3.3.2.jar:?]
at me.geek.mail.api.mail.MailSub.getItemInfo(MailSub.kt:188) ~[GeekMail-Pro-3.3.2.jar:?]
at me.geek.mail.common.menu.action.ItemMail.onClose(ItemMail.kt:45) ~[GeekMail-Pro-3.3.2.jar:?]
at me.geek.mail.common.menu.MenuListener.onClose(MenuListener.kt:54) ~[GeekMail-Pro-3.3.2.jar:?]
at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
at me.geek.mail.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[GeekMail-Pro-3.3.2.jar:?]
at me.geek.mail.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132) ~[GeekMail-Pro-3.3.2.jar:?]
at me.geek.mail.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130) ~[GeekMail-Pro-3.3.2.jar:?]
at me.geek.mail.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[GeekMail-Pro-3.3.2.jar:?]
at me.geek.mail.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76) ~[GeekMail-Pro-3.3.2.jar:?]
at me.geek.mail.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39) ~[GeekMail-Pro-3.3.2.jar:?]
at me.geek.mail.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39) ~[GeekMail-Pro-3.3.2.jar:?]
at me.geek.mail.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[GeekMail-Pro-3.3.2.jar:?]
at me.geek.mail.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[GeekMail-Pro-3.3.2.jar:?]
at me.geek.mail.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[GeekMail-Pro-3.3.2.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:git-Purpur-1970]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.4.jar:git-Purpur-1970]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.4.jar:git-Purpur-1970]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1592) ~[purpur-1.19.4.jar:git-Purpur-1970]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:3056) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:3049) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.handle(ServerboundContainerClosePacket.java:15) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.a(ServerboundContainerClosePacket.java:10) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.4.jar:git-Purpur-1970]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1369) ~[purpur-1.19.4.jar:git-Purpur-1970]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.4.jar:git-Purpur-1970]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1346) ~[purpur-1.19.4.jar:git-Purpur-1970]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1339) ~[purpur-1.19.4.jar:git-Purpur-1970]
at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[purpur-1.19.4.jar:git-Purpur-1970]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1970]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1970]_`
在这之后再也无法发送邮件
服务器版本：git-Purpur-1970 (MC: 1.19.4)

**Comment by liaojinmin** [comment]
待修复，目前版本还未支持到，

**Comment by liaojinmin** [comment]
已修复
