### ISSUE TITLE
MAIL_CMD创建模板无法正常使用

### ISSUE THREAD

**Issue by lizheyo77** [liaojinmin/GeekMail-Pro#4]
创建后应用会错误,版本1.18.2和1.19.2

**Comment by liaojinmin** [comment]
提交日志

**Comment by Baikele** [comment]
`[07:48:38] [Server thread/ERROR]: Could not pass event InventoryClickEvent to GeekMail-Pro v2.01
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[forge:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:593) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:578) ~[forge:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_147351_a(ServerPlayNetHandler.java:2269) ~[?:?]
        at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:34) ~[?:?]
        at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:12) ~[?:?]
        at net.minecraft.network.PacketThreadUtil.func_225383_a(PacketThreadUtil.java:22) ~[?:?]
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:886) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:169) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:869) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:863) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:849) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:781) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_341]
Caused by: kotlin1710.UninitializedPropertyAccessException: lateinit property cmds has not been initialized
        at me.Geek.GeekMail.modules.Mail_Cmd.giveAppendix(Mail_Cmd.kt:72) ~[?:?]
        at me.Geek.GeekMail.common.menu.MAction.getAppendix(MAction.kt:191) ~[?:?]
        at me.Geek.GeekMail.common.menu.MAction.access$getAppendix(MAction.kt:36) ~[?:?]
        at me.Geek.GeekMail.common.menu.MAction$action$1.onClick(MAction.kt:140) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor206.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_341]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_341]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[forge:?]
        ... 20 more`
