### ISSUE TITLE
模板bug MAIL_CMD = 指令包邮件

### ISSUE THREAD

**Issue by lizheyo77** [liaojinmin/GeekMail-Pro#5]
[16:48:52] [Server thread/INFO]: [GeekMail] 已加载 4 个邮件模板... (耗时 5 Ms)
[16:48:52] [Server thread/INFO]: [GeekMail] 菜单界面加载完成... (耗时 3 ms)
[16:48:57] [Server thread/INFO]: Orange_oo issued server command: /gkm pack 合金测试 Orange_oo
[16:48:57] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'gkm' in plugin GeekMail-Pro v2.03
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2389) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2200) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2181) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1403) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1396) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1374) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1256) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: kotlin1720.UninitializedPropertyAccessException: lateinit property cmds has not been initialized
	at me.Geek.GeekMail.modules.Mail_Cmd.sendMail(Mail_Cmd.kt:63) ~[GeekMail-Pro-2.03.jar:?]
	at me.Geek.GeekMail.command.player.CmdPack$command$1$1$2$2.invoke(CmdPack.kt:48) ~[GeekMail-Pro-2.03.jar:?]
	at me.Geek.GeekMail.command.player.CmdPack$command$1$1$2$2.invoke(CmdPack.kt:32) ~[GeekMail-Pro-2.03.jar:?]
	at me.Geek.GeekMail.taboolib.common.platform.command.CommandBuilder$CommandExecutor.exec(CommandBuilder.kt:192) ~[GeekMail-Pro-2.03.jar:?]
	at me.Geek.GeekMail.taboolib.common.platform.command.CommandBuilder$CommandBase.execute$process(CommandBuilder.kt:102) ~[GeekMail-Pro-2.03.jar:?]
	at me.Geek.GeekMail.taboolib.common.platform.command.CommandBuilder$CommandBase.execute$process(CommandBuilder.kt:94) ~[GeekMail-Pro-2.03.jar:?]
	at me.Geek.GeekMail.taboolib.common.platform.command.CommandBuilder$CommandBase.execute$process(CommandBuilder.kt:94) ~[GeekMail-Pro-2.03.jar:?]
	at me.Geek.GeekMail.taboolib.common.platform.command.CommandBuilder$CommandBase.execute(CommandBuilder.kt:115) ~[GeekMail-Pro-2.03.jar:?]
	at me.Geek.GeekMail.taboolib.common.platform.command.CommandRegisterKt$command$1.execute(CommandRegister.kt:23) ~[GeekMail-Pro-2.03.jar:?]
	at me.Geek.GeekMail.taboolib.platform.BukkitCommand$registerCommand$1.invoke$lambda-0(BukkitCommand.kt:70) ~[GeekMail-Pro-2.03.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	... 21 more

**Comment by liaojinmin** [comment]
已修复
